import type { Service, Step } from "./types";

const growthProcess: Step[] = [
  { title: "Understand", text: "Your offer, buyers, margins and what a good result looks like for you." },
  { title: "Analyse", text: "Current channels, tracking, competitors and where the biggest opportunity is." },
  { title: "Plan", text: "Targets, channels, budget split and the measures we will report on." },
  { title: "Execute", text: "Campaigns go live with tracking checked before spend scales." },
  { title: "Optimise", text: "Weekly changes based on what the data shows, not on assumptions." },
  { title: "Report", text: "Clear reporting on spend, leads, sales and what we are changing next." },
];

const companyProof = "$6M+ in ad spend managed and $27M+ in client revenue generated across our marketing work.";

export const marketingServices: Service[] = [
  {
    vertical: "marketing",
    slug: "b2b-lead-generation",
    name: "B2B Lead Generation",
    short: "B2B Lead Generation",
    metaTitle: "B2B & LinkedIn Lead Generation Company",
    h1: "B2B Lead Generation Company",
    metaDescription:
      "B2B and LinkedIn lead generation: decision-maker research, LinkedIn and email outreach, and booked sales meetings. 217 calls in 72 days from our own outreach.",
    outcome: "Qualified conversations, sales meetings and product demos with the decision makers you actually want to sell to.",
    summary: "ICP research, LinkedIn and email outreach, booked sales meetings.",
    problem: {
      intro: "Most B2B companies do not have a lead problem. They have a pipeline problem.",
      points: [
        "Sales depends on referrals, so growth is unpredictable.",
        "Outreach goes to the wrong people, or to the right people with the wrong message.",
        "Founders and sales teams spend their time prospecting instead of selling.",
        "Replies come in, but nobody follows up consistently or qualifies them.",
        "Automation tools were tried and produced spam, not meetings.",
      ],
    },
    whatWeDo: [
      "We run a structured appointment generation system. It starts with your ideal customer profile, identifies the decision makers who match it, and reaches them through personalised LinkedIn and email outreach with disciplined follow-ups.",
      "Our team manages the conversations, qualifies interest and books meetings or product demos directly into your calendar. Everything is logged in your CRM so you can see which segments and messages produce pipeline.",
      "This is not LinkedIn automation. Tools help us work at scale, but the targeting, messaging and conversation handling are done by people.",
    ],
    deliverables: [
      "Ideal customer profile and target account criteria",
      "Prospect research and decision-maker identification",
      "LinkedIn outreach with personalised messaging",
      "Email outreach and follow-up sequences",
      "Conversation management and lead qualification",
      "Appointment and product demo booking",
      "CRM integration and lead logging",
      "Weekly reporting and campaign optimisation",
    ],
    process: [
      { title: "Define the ICP", text: "Industries, company size, geography, roles and the problems your offer solves." },
      { title: "Build the list", text: "Researched decision makers who match the ICP, not bought databases." },
      { title: "Write the messaging", text: "Personalised openers and follow-ups tested by segment." },
      { title: "Run outreach", text: "LinkedIn and email sequences with consistent follow-ups." },
      { title: "Qualify and book", text: "Replies handled, interest qualified, meetings booked to your calendar." },
      { title: "Report and refine", text: "Reply, meeting and opportunity rates by segment, and what changes next." },
    ],
    whyUs: [
      "217 sales calls booked in 72 days through our own LinkedIn outreach system, using the same process we run for clients.",
      "Outreach, CRM and automation are handled by one team, so leads do not get lost between tools.",
      "Results depend on your offer, market and sales process. We set targets with you after reviewing them, and we do not promise a fixed number of meetings.",
    ],
    industries: ["saas-technology", "it-services", "education", "real-estate"],
    related: ["marketing/crm-marketing-automation", "marketing/performance-marketing", "pr/founder-thought-leadership", "development/saas-development"],
    caseStudies: ["linkedin-33-meetings-58-days", "linkedin-outbound-four-campaigns", "linkedin-217-sales-calls-72-days"],
    faqs: [
      { q: "How is this different from LinkedIn automation tools?", a: "Automation tools send messages. We decide who to contact and what to say, handle the replies, qualify interest and book meetings. The outcome we work towards is sales conversations, not message volume." },
      { q: "How many meetings can we expect?", a: "It depends on your market, offer, deal size and how narrow the ICP is. We set targets after reviewing these, and report reply, meeting and opportunity rates every week. Use our B2B Pipeline Calculator to estimate what your revenue target requires." },
      { q: "Do you use our LinkedIn profile?", a: "Outreach typically runs from the profiles of your founders or sales team, because buyers respond to people. We agree the approach and messaging with you before anything is sent." },
      { q: "Which markets can you target?", a: "We run outreach for businesses targeting markets including the UAE, USA, UK, Canada, Australia, Saudi Arabia, Kuwait, South Africa and Europe." },
      { q: "Will the leads be added to our CRM?", a: "Yes. Prospects, conversations and booked meetings are logged in your CRM, or in one we set up for you." },
    ],
  },
  {
    vertical: "marketing",
    slug: "performance-marketing",
    name: "Performance Marketing",
    short: "Performance Marketing",
    metaTitle: "Performance Marketing Agency | Google & Meta Ads",
    h1: "Performance Marketing Agency",
    metaDescription:
      "Google Ads, Meta Ads and LinkedIn Ads managed for leads and sales, with proper conversion tracking, audience strategy and transparent reporting.",
    outcome: "Paid campaigns that are measured on leads, sales and return on ad spend, not clicks.",
    summary: "Google, Meta and LinkedIn Ads for leads and sales.",
    problem: {
      intro: "Ad platforms make it easy to spend money and hard to know what it returned.",
      points: [
        "Conversion tracking is missing or counts the wrong actions.",
        "Campaigns are optimised for clicks and cheap leads that never buy.",
        "Budgets are spread across too many campaigns to learn anything.",
        "Reports show platform metrics, not revenue.",
      ],
    },
    whatWeDo: [
      "We plan and manage paid campaigns on Google Ads, Meta Ads and LinkedIn Ads, for lead generation and for e commerce sales.",
      "Every account starts with tracking: we make sure the platforms can see real conversions, then build audience strategy, creative testing, retargeting and budget allocation around them.",
    ],
    deliverables: [
      "Account and tracking audit",
      "Conversion tracking set-up (GA4, Meta Pixel and Conversions API, LinkedIn Insight)",
      "Campaign structure and audience strategy",
      "Ad copy and creative testing plan",
      "Retargeting campaigns",
      "Weekly optimisation",
      "Performance reporting tied to leads, sales and ROAS",
    ],
    process: growthProcess,
    useCases: [
      { title: "Google Ads", text: "Search, Performance Max and Shopping campaigns for buyers already looking for what you sell." },
      { title: "Meta Ads", text: "Facebook and Instagram campaigns for demand generation, lead forms and e commerce sales." },
      { title: "LinkedIn Ads", text: "Targeting by job title, company and industry for higher-value B2B offers." },
    ],
    whyUs: [
      companyProof,
      "Google Ads results in 2025 included 5.31x and 4.79x conversion value to cost on individual client accounts (figures from the client account dashboards).",
      "Results vary by product, margin and market. Past campaign results are not a guarantee of future performance.",
    ],
    industries: ["ecommerce-retail", "real-estate", "education", "saas-technology"],
    related: ["marketing/ecommerce-growth", "marketing/seo-aeo", "marketing/b2b-lead-generation", "marketing/crm-marketing-automation"],
    caseStudies: ["google-ads-2025-four-accounts"],
    faqs: [
      { q: "What budget do we need?", a: "Enough for the platform to collect conversion data each month. We recommend a starting budget after reviewing your market, average order or deal value and goals." },
      { q: "Which platform should we start with?", a: "If buyers search for your product, start with Google. For visual products and broad audiences, Meta. For B2B offers with a high deal value, LinkedIn. Many accounts use two together." },
      { q: "Who owns the ad accounts?", a: "You do. We work inside ad accounts owned by your business, so the data stays with you." },
    ],
  },
  {
    vertical: "marketing",
    slug: "seo-aeo",
    name: "SEO & AEO",
    short: "SEO & AEO",
    metaTitle: "SEO Agency | SEO Services & Answer Engine Optimization (AEO)",
    h1: "SEO & Answer Engine Optimization Agency",
    metaDescription:
      "Technical, on-page, content, local and e commerce SEO, plus answer engine optimisation so your business is found in Google and in AI answers.",
    outcome: "More of the right people find your business when they search on Google or ask an AI assistant.",
    summary: "Technical, content and local SEO, plus answer engine optimisation.",
    problem: {
      intro: "Organic search is the channel that keeps paying after the work is done, but only when the basics are right.",
      points: [
        "Important pages are not indexed, or compete with each other for the same keyword.",
        "Content answers questions nobody is asking.",
        "Local listings are incomplete, so nearby buyers find competitors.",
        "AI assistants describe your category without mentioning you.",
      ],
    },
    whatWeDo: [
      "SEO: we fix technical issues, structure pages around search intent, improve on-page content and build topical authority through content that supports your commercial pages. This covers local, e commerce, international and SaaS SEO, and Google Business Profile optimisation.",
      "AEO (answer engine optimisation) means structuring your content so AI assistants and search features can quote it accurately: clear answers to real questions, structured data, consistent business information across the web, and content that is cited by other sites.",
    ],
    deliverables: [
      "Technical SEO audit and fixes",
      "Keyword and search intent research",
      "Site structure and internal linking plan",
      "On-page optimisation of priority pages",
      "Content strategy and briefs",
      "Local SEO and Google Business Profile optimisation",
      "Structured data (schema) implementation",
      "AEO: question research, answer-ready content and entity consistency",
      "Monthly reporting on rankings, traffic and enquiries",
    ],
    process: growthProcess,
    whyUs: [
      "SEO and development under one roof: technical fixes are made by our own developers, not handed back to you.",
      "Every site we build starts with SEO-ready structure, so SEO work compounds instead of fighting the platform.",
    ],
    industries: ["ecommerce-retail", "education", "saas-technology", "real-estate"],
    related: ["marketing/social-media-content", "pr/digital-pr", "development/website-development", "marketing/performance-marketing"],
    faqs: [
      { q: "What is AEO?", a: "Answer engine optimisation is the practice of making your content easy for AI assistants and search features to understand and quote. It builds on SEO: clear answers, structured data and consistent information about your business." },
      { q: "How long does SEO take?", a: "Technical fixes can show results within weeks. Content and authority usually take several months. We report progress monthly so you can see what is moving." },
      { q: "Do you guarantee first-page rankings?", a: "No. Nobody controls Google's rankings. We commit to the work, the reporting and to improving the measures that lead to enquiries." },
    ],
  },
  {
    vertical: "marketing",
    slug: "social-media-content",
    name: "Social Media & Content",
    short: "Social Media & Content",
    metaTitle: "Social Media Marketing Agency | Content & LinkedIn",
    h1: "Social Media Marketing Agency",
    metaDescription:
      "Social media management, content strategy, LinkedIn and founder content, and content calendars that keep your brand consistent and visible.",
    outcome: "Consistent, useful content that keeps your brand visible to buyers between sales conversations.",
    summary: "Social media management, LinkedIn and founder content.",
    problem: {
      intro: "Posting regularly is hard to sustain alongside running a business.",
      points: [
        "Social profiles go quiet for weeks, then post in bursts.",
        "Content is about the company, not about the problems buyers have.",
        "Founders know they should post on LinkedIn but never find the time.",
      ],
    },
    whatWeDo: [
      "We plan, create and publish content for your social channels, with a calendar agreed in advance. For B2B companies we focus on LinkedIn, including content for founders and leaders written in their own voice.",
      "Content is planned around your services and buyers' questions, so it supports sales and search, not only engagement.",
    ],
    deliverables: [
      "Content strategy and pillars",
      "Monthly content calendar",
      "Post copy and graphics",
      "LinkedIn company and founder content",
      "Profile optimisation",
      "Publishing and community management",
      "Monthly performance report",
    ],
    process: growthProcess,
    whyUs: [
      "Content is connected to your SEO, ads and outreach, so one message runs across every channel.",
      "For founder visibility beyond social media, our PR team handles media and thought leadership.",
    ],
    industries: ["saas-technology", "it-services", "real-estate", "education"],
    related: ["pr/founder-thought-leadership", "marketing/b2b-lead-generation", "marketing/seo-aeo", "pr/digital-pr"],
    faqs: [
      { q: "Do you write in our founder's voice?", a: "Yes. We interview the founder, learn their views and language, and draft posts for their approval." },
      { q: "Which platforms do you manage?", a: "LinkedIn, Instagram and Facebook are the most common. We recommend platforms based on where your buyers spend time." },
    ],
  },
  {
    vertical: "marketing",
    slug: "crm-marketing-automation",
    name: "CRM & Marketing Automation",
    short: "Marketing Automation",
    metaTitle: "CRM & Marketing Automation Agency",
    h1: "CRM & Marketing Automation",
    metaDescription:
      "CRM set-up, lead nurturing, email and SMS automation and funnel automation, so every enquiry gets a fast, consistent follow-up.",
    outcome: "Every lead gets a fast, consistent follow-up, and you can see exactly where each one stands.",
    summary: "CRM set-up, lead nurturing, email and SMS automation.",
    problem: {
      intro: "Leads cost money. Most businesses lose a share of them after they arrive.",
      points: [
        "Enquiries wait hours or days for a first response.",
        "Follow-up depends on someone remembering.",
        "Leads from ads, the website and outreach sit in different places.",
        "Nobody can say which source produces customers.",
      ],
    },
    whatWeDo: [
      "We set up and run marketing and sales automation on CRM platforms: capturing leads from every source, responding instantly, nurturing them with email and SMS sequences, and alerting your team when someone is ready to talk.",
      "This page is about running acquisition and nurture workflows on a platform. If you need new software or system integrations engineered, see AI & Business Automation.",
    ],
    deliverables: [
      "CRM set-up and pipeline design",
      "Lead capture from forms, ads and outreach",
      "Instant response and follow-up automation",
      "Email and SMS nurture sequences",
      "Appointment booking and reminders",
      "Lead scoring and team notifications",
      "Source and conversion reporting",
    ],
    process: growthProcess,
    whyUs: [
      "We run these systems for our own lead generation, from enquiry form to booked consultation.",
      "Our developers handle custom integrations when a platform's built-in options are not enough.",
    ],
    industries: ["real-estate", "education", "saas-technology", "ecommerce-retail"],
    related: ["marketing/b2b-lead-generation", "development/ai-automation", "development/crm-erp-development", "marketing/performance-marketing"],
    faqs: [
      { q: "Which CRM platforms do you work with?", a: "We work with common CRM and marketing automation platforms and can recommend one if you do not have a CRM yet." },
      { q: "Can you connect our website and ad forms to the CRM?", a: "Yes. Website forms, ad lead forms and booking calendars can all feed the same pipeline." },
    ],
  },
  {
    vertical: "marketing",
    slug: "ecommerce-growth",
    name: "E Commerce Growth",
    short: "E Commerce Growth",
    metaTitle: "Ecommerce Marketing Agency | Meta & Google Ads",
    h1: "Ecommerce Marketing Agency",
    metaDescription:
      "E commerce growth across Meta Ads, Google Shopping, retargeting, conversion optimisation, email, SMS and retention. Results from D2C brands in 2025.",
    outcome: "Profitable online revenue growth from ads, conversion improvements and repeat customers.",
    summary: "Meta Ads, Google Shopping, CRO and retention for online stores.",
    problem: {
      intro: "E commerce margins leave little room for wasted spend.",
      points: [
        "Return on ad spend falls as budgets scale.",
        "Product feeds are incomplete, so Shopping ads underperform.",
        "Traffic arrives but the store does not convert.",
        "Customers buy once and never return.",
      ],
    },
    whatWeDo: [
      "We grow online stores across the full funnel: Meta and Google advertising, Google Shopping and product feed optimisation, retargeting, conversion rate optimisation on the store itself, and email and SMS for retention.",
      "Decisions are based on contribution and return on ad spend, not on platform-reported clicks.",
    ],
    deliverables: [
      "Store, tracking and ad account audit",
      "Meta Ads prospecting and retargeting",
      "Google Shopping and Performance Max",
      "Product feed optimisation",
      "Conversion rate optimisation recommendations",
      "Email and SMS retention flows",
      "Revenue and ROAS reporting",
    ],
    process: growthProcess,
    whyUs: [
      "In 2025 our team ran campaigns for D2C brands in apparel, beauty, ethnic wear, gifting and jewellery. Individual results are shown as case studies with their dates and sources.",
      companyProof,
      "Past results are specific to each brand and are not a promise of future performance.",
    ],
    industries: ["ecommerce-retail", "jewellery-diamonds"],
    related: ["marketing/performance-marketing", "development/ecommerce-development", "marketing/crm-marketing-automation", "marketing/seo-aeo"],
    caseStudies: ["kids-apparel-d2c-2025", "premium-womenswear-2025", "women-ethnic-wear-2025", "jewellery-brand-2025"],
    faqs: [
      { q: "Do you work with Shopify stores?", a: "Yes. We work with Shopify, WooCommerce and custom stores." },
      { q: "What ROAS should we expect?", a: "It depends on your margins, price point, category and how established the brand is. We agree a target ROAS based on your break-even point before scaling spend." },
    ],
  },
];
