import type { Service, Step } from "./types";

const buildProcess: Step[] = [
  { title: "Understand", text: "We learn the business, the users and what the system must achieve before any scope is written." },
  { title: "Plan", text: "Scope, functionality, integrations and a development roadmap you can approve line by line." },
  { title: "Design", text: "User journeys and interface design built around the agreed requirements." },
  { title: "Develop", text: "Our development team builds the approved solution in reviewable stages." },
  { title: "Test", text: "Functionality, integrations, usability and performance are tested before release." },
  { title: "Deploy", text: "The finished solution goes live in the environment you need." },
  { title: "Support", text: "Maintenance, improvements and technical support after launch, as required." },
];

const devProof = [
  "11+ years of development experience across websites, applications, SaaS, ERP, CRM and custom software.",
  "A team of 72 developers and technology professionals covering frontend, backend, mobile, database, UI/UX, integration and testing.",
];

export const developmentServices: Service[] = [
  {
    vertical: "development",
    slug: "website-development",
    name: "Website Development",
    short: "Website Development",
    metaTitle: "Website Development Company | Web Design & Development",
    h1: "Website Development Company",
    metaDescription:
      "Custom business and corporate websites built for speed, SEO and enquiries. 417+ websites developed across real estate, education, jewellery and more.",
    outcome: "A fast, search-ready website that explains your business clearly and turns visitors into enquiries.",
    summary: "Business, corporate and custom websites, redesigns and maintenance.",
    problem: {
      intro: "Most business websites were built once and left alone. Over time they stop doing their job.",
      points: [
        "Visitors cannot tell what you do or who you serve within the first few seconds.",
        "Pages load slowly on mobile, so people leave before they read anything.",
        "The site ranks for almost nothing because it was never structured for search.",
        "Enquiries arrive through a generic contact form with no context and no follow-up.",
        "Small updates need a developer, so content goes out of date.",
      ],
    },
    whatWeDo: [
      "We design and build websites around what your buyers need to know and do, not around a template. Each page has one job, one clear message and one next step.",
      "Every site is built with clean page structure, fast loading on mobile, search-friendly URLs and headings, and forms that capture the right information. You get an editing setup your team can actually use.",
      "If you already have a website, we can redesign it while keeping the search visibility you have earned, using proper redirects and content mapping.",
    ],
    deliverables: [
      "Sitemap, page structure and content plan",
      "Custom design for desktop and mobile",
      "Business, corporate or custom website build",
      "On-page SEO foundations: titles, meta descriptions, headings, schema, XML sitemap",
      "Enquiry forms connected to email or your CRM",
      "Analytics and conversion tracking set-up",
      "Redirect plan for redesigns",
      "Training for your team and ongoing maintenance options",
    ],
    process: buildProcess,
    useCases: [
      { title: "Corporate websites", text: "A credible presence for established companies that sell to other businesses or institutions." },
      { title: "Website redesign", text: "Modernising an outdated site without losing the rankings and traffic it already has." },
      { title: "Conversion-focused sites", text: "Service businesses that need the website to produce qualified enquiries, not just traffic." },
      { title: "Website maintenance", text: "Updates, security patches, backups and small improvements on an ongoing basis." },
    ],
    whyUs: [
      "417+ websites developed for businesses and institutions.",
      "Delivered websites for real estate, jewellery and diamond businesses, schools and colleges, e-commerce and oil and gas companies.",
      ...devProof,
    ],
    industries: ["real-estate", "education", "jewellery-diamonds", "ecommerce-retail"],
    related: ["development/ecommerce-development", "development/ui-ux-design", "marketing/seo-aeo", "development/web-application-development"],
    faqs: [
      { q: "How long does a business website take?", a: "It depends on the number of pages, the content you have ready and the functionality required. We give you a timeline after the scoping call, once we know the requirement." },
      { q: "Can you redesign our website without losing our Google rankings?", a: "Yes. We map every existing URL to its new page and set up permanent redirects, keep content that already ranks, and check indexing after launch." },
      { q: "Will we be able to update the website ourselves?", a: "Yes. We set up an editing system suited to how often you update content, and train your team to use it." },
      { q: "Do you offer website maintenance after launch?", a: "Yes. We provide ongoing maintenance, updates and technical support for websites we build and for existing websites." },
      { q: "What does a website cost?", a: "Cost depends on scope, design and functionality. Share your requirement in a 30 minute consultation and we will recommend an approach and give a quote." },
    ],
  },
  {
    vertical: "development",
    slug: "ecommerce-development",
    name: "E Commerce Development",
    short: "E Commerce Development",
    metaTitle: "Ecommerce Website Development | Shopify & WooCommerce",
    h1: "Ecommerce Website Development",
    metaDescription:
      "E commerce websites and custom commerce platforms with payments, catalogues, inventory and order management, built around how you actually sell.",
    outcome: "An online store or commerce platform that handles products, payments and orders without manual workarounds.",
    summary: "Online stores, WooCommerce, Shopify and custom commerce platforms.",
    problem: {
      intro: "Selling online gets complicated quickly once real orders start coming in.",
      points: [
        "The store platform cannot handle your catalogue, pricing rules or variants properly.",
        "Inventory, orders and invoices are reconciled by hand between systems.",
        "Checkout is slow or confusing on mobile, and carts are abandoned.",
        "The store is disconnected from your ERP, CRM, shipping or accounting tools.",
      ],
    },
    whatWeDo: [
      "We build e commerce websites on the platform that suits your products, order volume and team: WordPress with WooCommerce, Shopify, or a custom commerce platform when the business rules are too specific for an off-the-shelf store.",
      "The work covers product catalogue structure, customer accounts, payment gateway integration, order management and the integrations that remove manual work between your store and the rest of your business.",
    ],
    deliverables: [
      "Platform recommendation based on your catalogue and operations",
      "Store design for desktop and mobile",
      "Product catalogue, categories, variants and filters",
      "Payment gateway integration",
      "Customer accounts and order management",
      "Inventory and third-party integrations (ERP, shipping, accounting, CRM)",
      "Conversion tracking for ads and analytics",
    ],
    process: buildProcess,
    useCases: [
      { title: "D2C brands", text: "Consumer brands selling directly online that need a fast, mobile-first store." },
      { title: "B2B catalogues", text: "Suppliers with large catalogues, customer-specific pricing or enquiry-based ordering." },
      { title: "Jewellery and high-value products", text: "Detailed product attributes, certificates and enquiry flows alongside checkout." },
    ],
    whyUs: [
      "Development experience covering e commerce and retail businesses, with jewellery and diamond websites in our portfolio.",
      "Our marketing team runs e commerce advertising, so stores are built with tracking and conversion in mind from day one.",
      ...devProof,
    ],
    industries: ["ecommerce-retail", "jewellery-diamonds"],
    related: ["marketing/ecommerce-growth", "development/api-integration", "development/website-development", "marketing/performance-marketing"],
    faqs: [
      { q: "Should we use Shopify, WooCommerce or a custom platform?", a: "Shopify suits brands that want a managed platform and fast launch. WooCommerce suits businesses that want full control and already use WordPress. Custom platforms suit complex pricing, B2B ordering or deep ERP integration. We recommend one after reviewing your catalogue and operations." },
      { q: "Can you connect the store to our inventory or ERP?", a: "Yes. We integrate stores with inventory, ERP, accounting, shipping and CRM systems where those systems provide an API or data export." },
      { q: "Which payment gateways can you integrate?", a: "We integrate the payment gateways that support your markets and currencies. Tell us which gateways you use or prefer during the consultation." },
      { q: "Do you migrate existing stores?", a: "Yes. We migrate products, customers and order history where the source platform allows export, and set up redirects to protect search traffic." },
    ],
  },
  {
    vertical: "development",
    slug: "custom-software-development",
    name: "Custom Software Development",
    short: "Custom Software",
    metaTitle: "Custom Software Development Company | Business Systems",
    h1: "Custom Software Development Company",
    metaDescription:
      "Custom business software built around your processes: internal systems, portals, dashboards and workflow platforms that standard software cannot handle.",
    outcome: "Software that fits the way your business already works, instead of forcing your team to work around a generic tool.",
    summary: "Internal systems, workflow platforms and business-specific software.",
    problem: {
      intro: "Off-the-shelf software covers the average business. Yours may not be average.",
      points: [
        "Your team runs core processes on spreadsheets, email and WhatsApp.",
        "You pay for several tools that each do part of the job and do not talk to each other.",
        "Licensed software needs so much customisation that it is no longer cheaper.",
        "Managers cannot see what is happening without asking someone to compile a report.",
      ],
    },
    whatWeDo: [
      "We build business software around a specific requirement: an internal operations system, a workflow platform, a reporting dashboard or a portal for customers, vendors or staff.",
      "We start with the process, not the screens. Once we understand who does what and where it breaks, we design the system, build it in stages you can review, and support it after launch.",
    ],
    deliverables: [
      "Requirement analysis and process mapping",
      "Functional scope and development roadmap",
      "UI/UX design for each user role",
      "Web-based application development",
      "Role-based access and permissions",
      "Reports and dashboards",
      "Integrations with your existing systems",
      "Testing, deployment and support",
    ],
    process: buildProcess,
    useCases: [
      { title: "When to choose custom software", text: "When the process is a competitive advantage, when no product fits without heavy customisation, or when several tools need to become one system." },
      { title: "When off-the-shelf is better", text: "When the process is standard (payroll, basic accounting) and a mature product already does it well. We will tell you if that is the case." },
      { title: "Operations platforms", text: "Order processing, approvals, job tracking, field operations and other workflows specific to your business." },
    ],
    whyUs: [
      "74+ applications developed, beyond the websites in our portfolio.",
      "We build and operate our own software products, ACADMiN and eHeera, so we understand long-term product ownership, not only delivery.",
      ...devProof,
    ],
    industries: ["saas-technology", "education", "jewellery-diamonds", "it-services"],
    related: ["development/web-application-development", "development/crm-erp-development", "development/ai-automation", "development/api-integration"],
    faqs: [
      { q: "How do we know if we need custom software?", a: "If your team relies on workarounds, duplicate data entry or several disconnected tools for a core process, custom software is worth evaluating. In the consultation we will tell you honestly whether an existing product would do the job." },
      { q: "Can you work with our existing development team?", a: "Yes. We can build a complete product, a specific module, or support an existing team on a defined part of the work." },
      { q: "Who owns the software you build?", a: "Ownership and licensing terms are agreed in the project contract before development starts." },
      { q: "Can you take over an existing system?", a: "Yes. We review the existing code and infrastructure first, then recommend whether to improve it, extend it or rebuild parts of it." },
    ],
  },
  {
    vertical: "development",
    slug: "web-application-development",
    name: "Web Application Development",
    short: "Web Applications",
    metaTitle: "Web Application Development | Portals, Dashboards & Web Apps",
    h1: "Web Application Development",
    metaDescription:
      "Customer portals, admin dashboards, role-based systems and API-connected web applications designed around specific business workflows.",
    outcome: "A web application that lets your customers, staff or partners do real work online, securely and without friction.",
    summary: "Customer portals, admin dashboards and role-based web apps.",
    problem: {
      intro: "A website tells people about your business. A web application lets them actually do something in it, and that is a different job for software.",
      points: [
        "Customers email or call for information they should be able to see themselves.",
        "Partners and vendors exchange files and status updates manually.",
        "Admin teams manage records in several places with no single source of truth.",
        "Different users need to see different data, and permissions are hard to control.",
      ],
    },
    whatWeDo: [
      "We design and build browser-based applications: customer and business portals, admin dashboards, workflow applications and internal tools, each with proper login, roles and permissions.",
      "Applications are API-connected from the start, so they can exchange data with your CRM, ERP, payment gateway or mobile app when needed.",
    ],
    deliverables: [
      "User roles, permissions and workflows defined up front",
      "Interface design for each role",
      "Frontend and backend development",
      "Authentication and access control",
      "API layer for integrations and mobile apps",
      "Admin dashboard and reporting",
      "Testing, deployment and support",
    ],
    process: buildProcess,
    useCases: [
      { title: "Customer portals", text: "Customers view orders, documents, invoices, tickets or progress without contacting your team." },
      { title: "Business and partner portals", text: "Vendors, dealers or franchisees submit and track work in one place." },
      { title: "Admin dashboards", text: "One screen for the numbers and records managers need every day." },
    ],
    whyUs: [
      "Experience building web applications, business management systems, dashboards and portals for specific workflows.",
      "Our own SaaS products are web applications used by institutions and businesses every day.",
      ...devProof,
    ],
    industries: ["saas-technology", "education", "it-services", "real-estate"],
    related: ["development/saas-development", "development/custom-software-development", "development/ui-ux-design", "development/api-integration"],
    faqs: [
      { q: "What is the difference between a website and a web application?", a: "A website mainly presents information. A web application lets logged-in users create, update and manage data, such as orders, records or requests, with permissions controlling who sees what." },
      { q: "Can the web application work with a mobile app later?", a: "Yes. We build an API layer so a mobile app can use the same data and business rules." },
      { q: "How do you handle security?", a: "Role-based access, secure authentication, input validation, encrypted connections and testing are part of every build. Specific compliance needs are scoped during planning." },
    ],
  },
  {
    vertical: "development",
    slug: "mobile-app-development",
    name: "Mobile App Development",
    short: "Mobile App Development",
    metaTitle: "Mobile App Development Company | Android & iOS",
    h1: "Mobile App Development Company",
    metaDescription:
      "Android, iOS and cross-platform business and customer apps with API integration, notifications, authentication and payments where needed.",
    outcome: "A mobile app your customers or staff will actually use, connected to the systems your business already runs on.",
    summary: "Android, iOS and cross-platform apps for customers and teams.",
    problem: {
      intro: "Many apps are downloaded once and never opened again. Usually the cause is in the planning, not the code.",
      points: [
        "The app duplicates the website instead of doing something more useful on a phone.",
        "It does not connect to your backend, so data is out of date.",
        "Field teams still use paper or messaging apps because the internal app is too slow.",
      ],
    },
    whatWeDo: [
      "We build mobile applications for Android and iOS, natively or cross-platform depending on your users, budget and the features required.",
      "Every app is planned around a clear use: customers ordering or tracking, staff working in the field, or a mobile front end for an existing platform. We handle authentication, notifications, API integration, application dashboards and payment integration where applicable.",
    ],
    deliverables: [
      "Feature scope and user journeys",
      "Mobile UI/UX design",
      "Android, iOS or cross-platform development",
      "API integration with your backend",
      "Authentication and push notifications",
      "Payment integration where applicable",
      "Admin dashboard for managing app content and users",
      "App store submission support",
    ],
    process: buildProcess,
    useCases: [
      { title: "Customer apps", text: "Ordering, booking, tracking, loyalty or account management." },
      { title: "Employee and field apps", text: "Attendance, visits, inspections, deliveries or sales reporting from the field." },
      { title: "Companion apps", text: "A mobile front end for an existing web platform or SaaS product." },
    ],
    whyUs: [
      "Mobile applications built for customer, employee and business use cases across Android and iOS.",
      "One team for the app, the backend and the admin dashboard, so nothing falls between vendors.",
      ...devProof,
    ],
    industries: ["education", "ecommerce-retail", "saas-technology"],
    related: ["development/web-application-development", "development/ui-ux-design", "development/api-integration", "development/saas-development"],
    faqs: [
      { q: "Should we build native or cross-platform?", a: "Cross-platform suits most business and customer apps and reduces cost. Native suits apps that rely heavily on device hardware or need the highest performance. We recommend one once the features are clear." },
      { q: "Do you also build the backend and admin panel?", a: "Yes. We build or integrate the backend, APIs and admin dashboard the app needs." },
      { q: "Do you publish the app to the App Store and Google Play?", a: "We prepare the builds and support the submission process using your developer accounts." },
    ],
  },
  {
    vertical: "development",
    slug: "saas-development",
    name: "SaaS Product Development",
    short: "SaaS Development",
    metaTitle: "SaaS Development Company | SaaS MVP & Product Development",
    h1: "SaaS Development Company",
    metaDescription:
      "SaaS product development from MVP to scale: multi-user, subscription-based products with admin systems, customer portals and integrations.",
    outcome: "A SaaS product built to be sold, onboarded and scaled, by a team that runs SaaS products of its own.",
    summary: "SaaS MVPs, subscription products and scaling existing platforms.",
    problem: {
      intro: "Building software for one client is different from building a product many customers will pay for.",
      points: [
        "The MVP takes too long because the scope keeps growing.",
        "The product was built for one customer and is hard to configure for the next.",
        "Billing, onboarding and account management were left until the end.",
        "The architecture struggles as more customers and data arrive.",
      ],
    },
    whatWeDo: [
      "We take SaaS ideas from concept to a working product: defining the MVP, designing the product, and building multi-user, multi-account software with subscription logic, admin systems and customer portals.",
      "For existing products, we add modules, integrations and the improvements needed to scale.",
    ],
    deliverables: [
      "MVP definition and product roadmap",
      "Product design and user experience",
      "Multi-user and multi-account architecture",
      "Subscription, plans and billing integration",
      "Admin system and customer portal",
      "Third-party integrations",
      "Deployment, monitoring and ongoing development",
    ],
    process: buildProcess,
    whyUs: [
      "We built and run our own SaaS products: ACADMiN, an education ERP, and eHeera, jewellery management software.",
      "Experience developing cloud-based software products for specific industries and recurring business requirements.",
      ...devProof,
    ],
    industries: ["saas-technology", "education", "jewellery-diamonds"],
    related: ["development/web-application-development", "development/custom-software-development", "development/mobile-app-development", "development/ai-automation"],
    faqs: [
      { q: "What should a SaaS MVP include?", a: "Only what a first paying customer needs to get value: the core workflow, sign-up and login, basic account management and a way to pay. Everything else waits for real feedback." },
      { q: "Can you help after launch?", a: "Yes. We continue development, add modules and integrations, and support the product as it grows. Our marketing team can also run B2B lead generation for the product." },
      { q: "Do you sign NDAs?", a: "Yes. We are happy to sign an NDA before discussing product details." },
    ],
  },
  {
    vertical: "development",
    slug: "crm-erp-development",
    name: "CRM & ERP Development",
    short: "CRM & ERP",
    metaTitle: "CRM & ERP Software Development Company",
    h1: "CRM & ERP Software Development",
    metaDescription:
      "Custom CRM and ERP development and implementation: lead management, sales workflows, operations, reporting and role-based access in one system.",
    outcome: "One system for your leads, customers and operations, so information stops living in separate tools and spreadsheets.",
    summary: "Custom CRM, ERP and business management systems.",
    problem: {
      intro: "As a business grows, information spreads across people and tools.",
      points: [
        "Leads are tracked in spreadsheets and follow-ups are missed.",
        "Sales, operations and accounts each keep their own version of the truth.",
        "Reports take days to compile and are out of date when they arrive.",
        "Generic CRM or ERP products do not match how your business works.",
      ],
    },
    whatWeDo: [
      "CRM: we build or customise customer and lead management systems covering enquiries, sales pipelines, communication, follow-ups and reporting.",
      "ERP: we develop integrated platforms that bring several business functions, such as sales, inventory, purchasing, HR and finance, into one digital system with role-based access.",
      "We also implement and customise existing CRM platforms when a custom build is not necessary.",
    ],
    deliverables: [
      "Process mapping across departments",
      "Lead, customer and sales pipeline management",
      "Operations, inventory or project modules as required",
      "Role-based access and approval workflows",
      "Reports and management dashboards",
      "Data migration from spreadsheets or existing systems",
      "Integrations with accounting, payments, email and messaging",
      "Training and support",
    ],
    process: buildProcess,
    whyUs: [
      "We built ACADMiN, an education ERP that brings admissions, fees, examinations, HR, payroll and more into one system.",
      "Experience developing ERP systems and CRM platforms for clients across industries.",
      ...devProof,
    ],
    industries: ["education", "jewellery-diamonds", "real-estate", "it-services"],
    related: ["development/custom-software-development", "development/api-integration", "marketing/crm-marketing-automation", "development/ai-automation"],
    faqs: [
      { q: "Should we build a custom CRM or buy a SaaS CRM?", a: "Buy it if your sales process looks like most sales processes. A SaaS CRM is live in weeks, somebody else maintains it, and you pay per user forever. Build it when your pipeline, your data model or your integrations are genuinely unusual, when per-user pricing has become the larger cost, or when the data cannot sit on somebody else's platform. We will tell you which one your situation is after looking at how your team actually sells, and we have no reason to push you towards the build." },
      { q: "Should we build a custom ERP or buy a SaaS ERP?", a: "The honest default is to buy. ERP touches finance, inventory, purchasing and HR at once, and a custom build is a long project before it returns anything. Buying makes sense when a standard product covers most of what you do and you are willing to change some processes to fit it. Build when the operation is the business, for example manufacturing or distribution with rules no product supports, or when you have already outgrown a product and are paying for workarounds. A common middle path is to buy the core and build only the modules that are specific to you." },
      { q: "What happens to the systems and spreadsheets we use today?", a: "They get migrated, not abandoned. We export what can be exported from your existing systems and spreadsheets, map it to the new structure, and have your team check it against their own records before go-live. Most projects run the old and new side by side for a short period so nobody is working blind." },
    ],
  },
  {
    vertical: "development",
    slug: "ai-automation",
    name: "AI & Business Automation",
    short: "AI & Automation",
    metaTitle: "AI Automation Agency | AI Agents & Workflows",
    h1: "AI Automation Agency",
    metaDescription:
      "AI applications, AI agents and workflow automation engineered around real business processes: sales, customer communication, CRM and internal operations.",
    outcome: "Less repetitive manual work, with AI and automation built into the systems your team already uses.",
    summary: "AI agents, AI-enabled systems and workflow automation.",
    problem: {
      intro: "Teams lose hours every week to work a system could do.",
      points: [
        "Staff copy data between email, spreadsheets, CRM and accounting tools.",
        "Customer questions wait for a person even when the answer is routine.",
        "Documents, enquiries and requests are read and sorted by hand.",
        "AI tools were tried, but nothing was connected to real business data.",
      ],
    },
    whatWeDo: [
      "We engineer automation and AI into business systems. That means mapping a process, deciding which steps should be automated, which need AI and which need a person, then building it into your tools with proper logging and human review where it matters.",
      "This page covers building systems. If you need marketing workflows such as lead nurturing and email sequences run on an existing platform, see CRM & Marketing Automation.",
    ],
    deliverables: [
      "Process review and automation opportunity list",
      "Workflow automation between your applications",
      "AI agents for defined tasks, with human approval steps",
      "AI features inside existing applications",
      "CRM, sales and customer communication automation",
      "Monitoring, logs and error handling",
    ],
    process: buildProcess,
    useCases: [
      { title: "Enquiry handling", text: "Incoming enquiries are classified, enriched and routed to the right person with a draft reply." },
      { title: "Sales automation", text: "Lead assignment, follow-up reminders and CRM updates happen without manual entry." },
      { title: "Document processing", text: "Information is extracted from invoices, forms or applications and entered into your system for review." },
      { title: "Internal processes", text: "Approvals, notifications and reporting run on rules instead of reminders." },
    ],
    whyUs: [
      "AI and automation are a dedicated capability in our 72-person technology team.",
      "We build the surrounding systems too, so automation is connected to your CRM, ERP and applications rather than bolted on.",
      "11+ years of development experience across business software.",
    ],
    industries: ["it-services", "saas-technology", "education", "real-estate"],
    related: ["development/api-integration", "development/crm-erp-development", "development/custom-software-development", "marketing/crm-marketing-automation"],
    faqs: [
      { q: "Where should we start with AI?", a: "Start with one high-volume, repetitive process where mistakes are easy to check. We help you pick it, measure the time it takes today, and automate it first." },
      { q: "Is our data safe when using AI?", a: "We choose providers and settings that match your data requirements, keep credentials on the server, and add human review for sensitive actions." },
      { q: "What is the difference between this and marketing automation?", a: "Here we engineer new systems and integrations. Marketing automation configures and runs lead nurturing and campaigns on platforms such as a CRM." },
    ],
  },
  {
    vertical: "development",
    slug: "api-integration",
    name: "API & System Integration",
    short: "API Integration",
    metaTitle: "System Integration & API Integration Services",
    h1: "API and System Integration Services",
    metaDescription:
      "API development and integration of CRM, ERP, payment gateways and third-party platforms so your business systems share data automatically.",
    outcome: "Your systems share data automatically, so nobody re-types the same information twice.",
    summary: "API development, third-party, CRM, ERP and payment integrations.",
    problem: {
      intro: "Most businesses run on several systems that were never designed to work together.",
      points: [
        "Orders, leads or invoices are re-entered from one system into another.",
        "Data is inconsistent because each system is updated at a different time.",
        "A new tool cannot be adopted because it does not connect to the old one.",
      ],
    },
    whatWeDo: [
      "We build APIs for your own applications and integrate third-party platforms: CRMs, ERPs, payment gateways, accounting software, marketing tools and industry systems.",
      "Integrations include error handling and monitoring, so failures are visible and fixable instead of silently losing data.",
    ],
    deliverables: [
      "Integration map of your systems and data flows",
      "API design and development",
      "Third-party API integration",
      "CRM, ERP and payment gateway integration",
      "Data mapping and transformation",
      "Logging, retries and failure alerts",
      "Integration documentation",
    ],
    process: buildProcess,
    whyUs: [
      "API and integration is a dedicated function in our technology team.",
      "Integration experience across applications, payment systems and existing business platforms.",
      "11+ years of development experience.",
    ],
    industries: ["ecommerce-retail", "saas-technology", "it-services"],
    related: ["development/ai-automation", "development/crm-erp-development", "development/web-application-development", "development/ecommerce-development"],
    faqs: [
      { q: "Can you integrate a system that has no API?", a: "Sometimes. Options include file-based exchange, database-level integration or official export tools. We do not use methods that break a provider's terms." },
      { q: "Do you maintain integrations after launch?", a: "Yes. Third-party APIs change, so we offer monitoring and maintenance for integrations we build." },
    ],
  },
  {
    vertical: "development",
    slug: "ui-ux-design",
    name: "UI/UX Design",
    short: "UI/UX Design",
    metaTitle: "UI/UX Design Agency | Website, App & SaaS Product Design",
    h1: "UI/UX Design Agency",
    metaDescription:
      "UI/UX design for websites, web applications, SaaS products, dashboards and mobile apps: user journeys, wireframes and interface design.",
    outcome: "Interfaces people understand the first time they use them, designed before a line of code is written.",
    summary: "User journeys, wireframes and interface design for sites and apps.",
    problem: {
      intro: "Poor design is expensive to fix after development.",
      points: [
        "Users cannot find key actions, so support requests pile up.",
        "Every screen looks different because there is no design system.",
        "Dashboards show data but do not help anyone make a decision.",
      ],
    },
    whatWeDo: [
      "We design websites, application interfaces, SaaS products, dashboards and mobile apps, starting from user journeys and wireframes before moving to visual design.",
      "Designs are delivered as reusable components so development is faster and the product stays consistent as it grows.",
    ],
    deliverables: [
      "User roles and journeys",
      "Wireframes for key flows",
      "Visual interface design for desktop and mobile",
      "Design system and reusable components",
      "Clickable prototypes for review",
      "Developer handover",
    ],
    process: [
      { title: "Understand", text: "Users, goals and the tasks the interface must support." },
      { title: "Map", text: "User journeys and information structure." },
      { title: "Wireframe", text: "Layouts for key screens, reviewed before visual design." },
      { title: "Design", text: "Visual design and a component library." },
      { title: "Prototype", text: "Clickable flows to test with your team or users." },
      { title: "Hand over", text: "Specifications and assets for development." },
    ],
    whyUs: [
      "UI/UX design sits inside our development team, so designs are buildable and tested against real constraints.",
      "Experience designing websites, application interfaces and our own SaaS products.",
    ],
    industries: ["saas-technology", "education", "ecommerce-retail"],
    related: ["development/website-development", "development/web-application-development", "development/saas-development", "development/mobile-app-development"],
    faqs: [
      { q: "Can you design only, without development?", a: "Yes. We can deliver design and a developer handover for your own team to build." },
      { q: "Can you redesign an existing application?", a: "Yes. We start by reviewing how people use the current product, then redesign the flows that cause the most friction first." },
    ],
  },
];
